### ISSUE TITLE
elmah.io target last in list

### ISSUE THREAD

**Issue by ThomasArdal** [NLog/NLog.github.io#117]
The new searchable targets list is awesome. But I just noticed that the elmah.io target is last in the "Integrations (Cloud)" list. Personally, I don't care where the target is on the list, but it just looks a bit weird that everything else is sorted alphabetically. I looked in the code and cannot seem to figure out why it's added as the last item. The target is added [here](https://github.com/NLog/NLog.github.io/blob/0bfd2d68410251fd79b07c36739f2566a9b65dbf/config/targets.json#L544), but it doesn't look like the order in this file is used when generating the website.

**Comment by 304NotModified** [comment]
Hi, that's a bug then. It should be sorted.

**Comment by 304NotModified** [comment]
I think I know the issue, the `_.orderBy(list, function (item) { return item.name })` is behaving akward,

It orders like this: A,B,a,b etc

**Comment by ThomasArdal** [comment]
I see. A quick fix would, of course, be to rename elmah.io to Elmah.io. I would be a bit unhappy with this solution since the product name is all lowercase.

**Comment by 304NotModified** [comment]
I think #118 will fix this :)

**Comment by 304NotModified** [comment]
![image](https://user-images.githubusercontent.com/5808377/58820360-b1bdbf00-8632-11e9-8061-ed0c72841b1b.png)

🎉
