### ISSUE TITLE
nlog-project.org - feed not well-formed

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.github.io#121]
https://nlog-project.org/feed/

![image](https://user-images.githubusercontent.com/11509660/59965270-0bb3f500-950c-11e9-87ae-614ce935e641.png)

**Comment by 304NotModified** [comment]
Fixed, but not tested with a RSS reader. Dunno what supports RSS these days

**Comment by 304NotModified** [comment]
Ow IE yeeh

![image](https://user-images.githubusercontent.com/5808377/59969855-90c4fb80-9558-11e9-900b-f48858a1919a.png)
