### ISSUE TITLE
Consider moving appsettings schema to schemastore

### ISSUE THREAD

**Issue by ThomasArdal** [NLog/NLog.github.io#163]
We have discussed the [NLog schema](https://github.com/NLog/NLog.github.io/blob/master/schemas/appsettings.schema.json) for `appsettings.json` files previously. Now that Microsoft finally seems to have embraced the schema available on SchemaStore (https://devblogs.microsoft.com/aspnet/intellisense-for-appsettings-json/), maybe now would be a good time to move the NLog schema to the [appsettings.json schema on SchemaStore](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/appsettings.json). Or what are your thoughts on this? As an alternative, the recent code from the `appsettings.json` schema on SchemaStore should be used for NLog's schema, rather than the current code which is a copy of an early attempt I made 👍

**Comment by ThomasArdal** [comment]
And just a quick comment. If this is something you think is a good idea, I can do the work. I just didn't want to do it before clearing it with you guys.

**Comment by 304NotModified** [comment]
Sounds good! :) Would be great if you could start on this :) 👍 👍

**Comment by ThomasArdal** [comment]
https://github.com/SchemaStore/schemastore/pull/1527

I will await the result of that PR and iterate back on this repo when the schema addition is merged. I think the description [here](https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json) should be changed to support NLog's schema now being in the official one, right.

**Comment by ThomasArdal** [comment]
Ok, so the NLog config is now in the official `appsettings.json` schema 🥳. Once that is live, I would like to update the following text on https://github.com/NLog/NLog.Extensions.Logging/wiki/NLog-configuration-with-appsettings.json:

---

## JSON Schema

JSON Schema could be found here: https://nlog-project.org/schemas/appsettings.schema.json.

Please note it has no auto-completion for the target properties

---

To maybe something like this:

---

## JSON Schema

JSON Schema is included in the official schema for `appsettings.json` files available at https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/appsettings.json.

Please note it has no auto-completion for the target properties

---

Let me know what you think :smile:

**Comment by 304NotModified** [comment]
Sounds good! Thanks!

**Comment by ThomasArdal** [comment]
The description is updated and closing this issue 😄
