### ISSUE TITLE
Cleanup Platforms for config items ?

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.github.io#182]
Consider to cleanup platforms and just have `.NET Framework` and `.NET Standard`. Further platform-details should be displayed on wiki-page.
```json
        "platforms": [
            "net35",
            "net40",
            "net45",
            "netstandard1.3",
            "netstandard1.5",
            "netstandard2.0",
            "ios",
            "android",
            "mono",
            "wp8"
        ],
```

Notice .NET Framework 4.6.1 supports .NET Standard 2.0, so maybe just remove the platforms all together? (And .NET Standard 1.3 + 1.5 are no longer super important).

**Comment by snakefoot** [comment]
Created  #183 as initial cleanup, before adding new NLog 5.0 layout-renderers.

**Comment by snakefoot** [comment]
I'm happy now. .NET Framework is here to stay until 2028

**Comment by 304NotModified** [comment]
As 4.6.1 is no longer supported,  we *could* go to .net standard 2+ only in the future

**Comment by 304NotModified** [comment]
Oops i missed  .net 3.5 sp1 😅

**Comment by snakefoot** [comment]
.NET35 and. NET48 is forever



Sent from my Galaxy



-------- Original message --------
From: Julian Verdurmen ***@***.***>
Date: 19/05/2022 22:45 (GMT+01:00)
To: "NLog/NLog.github.io" ***@***.***>
Cc: Rolf Kristensen ***@***.***>, State change ***@***.***>
Subject: Re: [NLog/NLog.github.io] Cleanup Platforms for config items ? (Issue #182)


As 4.6.1 is no longer supported, we could go to .net standard 2+ only in the future
