### ISSUE TITLE
API docs: some links are broken

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.github.io#22]
For example: http://nlog-project.org/documentation/v3.2.1/html/T_NLog_Targets_ChainsawTarget.htm

the 'more' link is broken. (links to `http://nlog-project.org/documentation/v3.2.1/html/config.html`)

**Comment by 304NotModified** [comment]
http://nlog-project.org/documentation/v4.3.0/html/T_NLog_Targets_ChainsawTarget.htm

**Comment by snakefoot** [comment]
Created https://github.com/NLog/NLog/pull/4773 to fix the broken links

**Comment by snakefoot** [comment]
Believe links are fixed with NLog v5 Documentation:

http://nlog-project.org/documentation/v5.0.0/html/T_NLog_Targets_ChainsawTarget.htm
