### ISSUE TITLE
some css are broken

### ISSUE THREAD

**Issue by AzureZeng** [NLog/NLog.github.io#229]
![image](https://user-images.githubusercontent.com/19504193/235079339-210e253e-fab6-41ba-908a-1ed5ebaca872.png)
As below, this website becomes difficult to read because the broken css

**Comment by 304NotModified** [comment]
@snakefoot any idea what happend? I see the same issue but I dont have access to my laptop this weekend

**Comment by snakefoot** [comment]
No idea. I saw this

> Download action repository 'actions/checkout@v3' (SHA:8e5e7e5ab8b370d6c329ec480221332ada57f0ab)
> Download action repository 'actions/jekyll-build-pages@v1' (SHA:0143c158f4fa0c5dcd99499a5d00859d79f70b0e)
> **Warning:** Failed to download action 'https://api.github.com/repos/actions/jekyll-build-pages/tarball/0143c158f4fa0c5dcd99499a5d00859d79f70b0e'. Error: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
> **Warning:** Back off 29.403 seconds before retry.
> Download action repository 'actions/upload-pages-artifact@v1' (SHA:64bcae551a7b18bcb9a09042ddf1960979799187)

> https://github.com/NLog/NLog.github.io/actions/runs/4790889379/jobs/8520601729

https://github.com/NLog/NLog.github.io/actions/runs/4790889379/jobs/8520601729

Now I re-ran the the pipeline, and things looks good again:
