### ISSUE TITLE
XSD schema URLs not accessible

### ISSUE THREAD

**Issue by luigiberrettini** [NLog/NLog.github.io#74]
All URLs used in config files and XSD referencing schemas present in the `schemas` folder are broken.

An example of the change in URL:
http://www.nlog-project.org/schemas/NLog.xsd became https://nlog-project.org/schemas/NLog.xsd

It would be better if you could restore the old URLs, otherwise every user has to update their link and also the XSD files in the schemas folder should be updated

**Comment by 304NotModified** [comment]
Hi,

It's seem that the redirect from www to naked domain is "dumb". I will try to fix that.
