### ISSUE TITLE
Config options for NLog.Web shows wrong package + missing stuff

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.github.io#81]
When going to this URL:

https://nlog-project.org/config/?tab=layout-renderers&search=package:nlog.web

- [x] Then one sees the following `${configsetting]` item:

![image](https://user-images.githubusercontent.com/11509660/50787349-74891700-12b6-11e9-817b-fbf89b6f0b25.png)

#### Missing 

Btw. the following pages are missing:

- [x] https://github.com/NLog/NLog/wiki/AspNet-Request-ContentType-layout-renderer (AspNetCore only)
- [x] https://github.com/NLog/NLog/wiki/AspNet-Environment-layout-renderer (AspNetCore only)
- [x] https://github.com/NLog/NLog/wiki/AspNet-WebRootPath-layout-renderer (AspNet + AspNetCore)
- [x] https://github.com/NLog/NLog/wiki/AspNet-AppBasePath-layout-renderer (AspNet + AspNetCore)
- [x] [NLog.ETW](https://github.com/NLog/NLog.Etw) is missing 

### Enhancements 
- [x] `GrowlNotify` should probably be moved into `Integrations (GUI tools)`
- [x]  `R7 InsightOps` should probably be moved into `Integrations (Cloud)`
- [x]  `EventLog` from `NLog.WindowsEventLog` should probably say "Writes log message to the Windows EventLog **for NetCore**".

**Comment by 304NotModified** [comment]
Partly solved, thanks for the feedback :)

**Comment by 304NotModified** [comment]
8/9

**Comment by 304NotModified** [comment]
done!
